apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: krwhut5ps-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:56c4c6d8f9ed1d63c5c25c147dfa319098f64d08@sha256:8720222c41f921460e9b891449e006d95b3456d79a1af0b4b5fc7273c6f9ea18
          name: container-image
