apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: krwhut5ps-python
  janus-idp.io/tekton: krwhut5ps-python
  backstage.io/kubernetes-id: krwhut5ps-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: krwhut5ps-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
